sudo: required
services:
  - docker

before_install:
  - docker image build -t rajithsiriwardana/docker-react -f Dockerfile.dev .

script: 
  - docker run rajithsiriwardana/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-106770609032"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws-access-key
  secret_access_key: $aws-secret-key
